version: "3.9"

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ioopm
      MYSQL_USER: ioopm
      MYSQL_PASSWORD: ioopm
    networks:
      - bubifysite
  bubify:
    depends_on:
      - db
    image: bubify
    links:
      - db:db
    ports:
      - "801:80"
    restart: unless-stopped
    environment:
      AU_DB_HOST: db
      AU_HOSTNAME: localhost
      AU_DB_USER: root
      AU_DB_PASSWORD: root
      AU_BACKEND_HOST: https://localhost/api
      AU_FRONTEND_HOST: https://localhost
      AU_APP_API: https://localhost/api
      AU_APP_WEBSOCKET: https://localhost/api/portfolio
    networks:
      - bubifysite
  nginx:
    image: nginx:latest
    container_name: reverse
    volumes:
      - ./ssl/reverse_proxy.conf:/etc/nginx/conf.d/default.conf
      - ./ssl/bubify.cert:/etc/nginx/cert/bubify.cert
      - ./ssl/bubify.key:/etc/nginx/cert/bubify.key
    ports:
      - 80:80
      - 443:443
    networks:
      - bubifysite
    links:
      - bubify:bubify

volumes:
  db_data: {}
networks:
  bubifysite:


